Fuel/Controllers/FuelCommandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Fuel.Helper;
using Fuel.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;


namespace Fuel.Controllers
{

    public class FuelCommandsController : Controller
    {
        HelpingAPI _api = new HelpingAPI();

        public async Task<IActionResult> ViewAllFuelings(string searchString)
        {
            List<BasicLibrary.Models.Fuel> fuels = new List<BasicLibrary.Models.Fuel>();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync("api/Fuels");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                fuels = JsonConvert.DeserializeObject<List<BasicLibrary.Models.Fuel>>(result);
            }
            if (searchString != null)
            {
                return View(fuels.Where(x => x.RegistrationNr.Contains(searchString)));
            }
            else return View(fuels);
        }

        

        public async Task<IActionResult> FuelDetails(int Id)
        {
            var fuels = new BasicLibrary.Models.Fuel();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync($"api/Fuels/{Id}");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                fuels = JsonConvert.DeserializeObject<BasicLibrary.Models.Fuel>(result);
            }
            return View(fuels);
        }




        public IActionResult CreateFuelings()
        {
            return View();
        }
       
        [HttpPost]
        public IActionResult CreateFuelings(BasicLibrary.Models.Fuel fuels)
        {
            HttpClient client = _api.Initial();
            var postTask = client.PostAsJsonAsync<BasicLibrary.Models.Fuel>("api/Fuels", fuels);
            postTask.Wait();

            var result = postTask.Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("ViewAllFuelings");
            }
            return View();
        }


        public async Task<IActionResult> FuelEdit(int Id)
        {
            var fuels = new BasicLibrary.Models.Fuel();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync($"api/Fuels/{Id}");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                fuels = JsonConvert.DeserializeObject<BasicLibrary.Models.Fuel>(result);
            }
            return View(fuels);
        }


        [HttpPost]
        public IActionResult FuelEdit(int Id, BasicLibrary.Models.Fuel fuels)
        {
            HttpClient client = _api.Initial();
            var postTask = client.PutAsJsonAsync<BasicLibrary.Models.Fuel>($"api/Fuels/{Id}", fuels);
            postTask.Wait();

            var result = postTask.Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("ViewAllFuelings");
            }
            return View();
        }



        public async Task<IActionResult> FuelDelete(int Id)
        {
            var fuels = new BasicLibrary.Models.Fuel();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync($"api/Fuels/{Id}");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                fuels = JsonConvert.DeserializeObject<BasicLibrary.Models.Fuel>(result);
            }
            return View(fuels);
        }


        [HttpPost]
        public async Task<IActionResult> FuelDelete(int Id, BasicLibrary.Models.Fuel x)
        {
            HttpClient client = _api.Initial();
            await client.DeleteAsync($"api/Fuels/{Id}");
            return RedirectToAction("ViewAllFuelings");
        }

    }
}

Fuel/Views/FuelCommands/CreateFuelings.cshtml
@using Fuel.Models
@model BasicLibrary.Models.Fuel
@inject Fuel.Models.DropDownListVehicles vehicleService

@{
    ViewData["Title"] = "CreateFuelings";
}
 
<h4 style="color:purple; margin-top:50px; font-weight:bold">Create a new Fuel Record</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateFuelings">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RegistrationNr" class="control-label"></label>
                @Html.DropDownList("RegistrationNr",
                        new SelectList(vehicleService.GetVechiclesAsync()),
                        "Select Reg Nr.",
                        new { @class = "form-control" })
                <span asp-validation-for="RegistrationNr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfFueling" class="control-label"></label>
                <input asp-for="DateOfFueling" class="form-control" />
                <span asp-validation-for="DateOfFueling" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Area" class="control-label"></label>
                <input asp-for="Area" class="form-control" />
                <span asp-validation-for="Area" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-primary" style="background-color:greenyellow" /> |
                @Html.ActionLink("Back to Fuels", "ViewAllFuelings", "FuelCommands", new { }, new { @class = "btn btn-outline-primary", @style = "background-color:greenyellow" })
            </div>
        </form>
    </div>
</div>

Fuel/Views/FuelCommands/FuelDelete.cshtml
@model BasicLibrary.Models.Fuel

@{
    ViewData["Title"] = "FuelDelete";
}

<h4 style="color:purple; margin-top:50px; font-weight:bold" >Are you sure you want to delete this record?</h4>
<hr />
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationNr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegistrationNr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfFueling)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfFueling)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Area)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Area)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="FuelDelete">
        <input type="submit" value="Delete" class="btn btn-outline-primary" style="background-color:red" /> |
        @Html.ActionLink("Back to Fuels", "ViewAllFuelings", "FuelCommands", new { }, new { @class = "btn btn-outline-primary", @style = "background-color:greenyellow" })
    </form>
</div>

Fuel/Views/FuelCommands/FuelDetails.cshtml
@model BasicLibrary.Models.Fuel

@{
    ViewData["Title"] = "FuelDetails";
}

<h4 style="color:purple; margin-top:50px; font-weight:bold">Fuel Record Details</h4>
<hr />
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationNr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegistrationNr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfFueling)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfFueling)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Area)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Area)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "FuelEdit", "FuelCommands", new { id = Model.Id }, new { @class = "btn btn-outline-primary", @style = "background-color:greenyellow" }) |
    @Html.ActionLink("Back to Fuels", "ViewAllFuelings", "FuelCommands", new { }, new { @class = "btn btn-outline-primary", @style = "background-color:greenyellow" })
</div>

Fuel/Views/FuelCommands/FuelEdit.cshtml
@model BasicLibrary.Models.Fuel

@{
    ViewData["Title"] = "FuelEdit";
}

<h4 style="color:purple; margin-top:50px; font-weight:bold">Edit Fuel Record</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="FuelEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RegistrationNr" class="control-label"></label>
                <input asp-for="RegistrationNr" class="form-control" />
                <span asp-validation-for="RegistrationNr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfFueling" class="control-label"></label> 
                <input asp-for="DateOfFueling" class="form-control" />
                <span asp-validation-for="DateOfFueling" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Area" class="control-label"></label>
                <input asp-for="Area" class="form-control" />
                <span asp-validation-for="Area" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-outline-primary" style="background-color:greenyellow" /> |
                @Html.ActionLink("Back to Fuels", "ViewAllFuelings", "FuelCommands", new { }, new { @class = "btn btn-outline-primary", @style = "background-color:greenyellow" })
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Fuel/Views/FuelCommands/ViewAllFuelings.cshtml
@model IEnumerable<BasicLibrary.Models.Fuel>

@{
    ViewData["Title"] = "ViewAllFuelings";
}

    <div class="input-w" style="margin-top:40px">
        <form asp-controller="FuelCommands" asp-action="ViewAllFuelings">
            <p>
                <input type="button" class="btn btn-outline-primary" style="background-color:orange; margin-right:20px;" value="Create New" onclick="location.href='@Url.Action("CreateFuelings", "FuelCommands")'" />
                Reg. No. <input type="text" name="SearchString">
                <input type="submit" value="Filter" asp-controller="FuelCommands" asp-action="ViewAllFuelings" class="btn btn-outline-primary" style="background-color:gold" />
            </p>
        </form>
    </div>




<table class="table" id="table1" style="margin-top:50px; margin-bottom:50px">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RegistrationNr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfFueling)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Area)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RegistrationNr)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfFueling)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Area)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.ActionLink("Edit", "FuelEdit", "FuelCommands", new { id = item.Id }, new { @class = "btn btn-info" })
                    @Html.ActionLink("Detail", "FuelDetails", "FuelCommands", new { id = item.Id }, new { @class = "btn btn-info" })
                    @Html.ActionLink("Delete", "FuelDelete", "FuelCommands", new { id = item.Id }, new { @class = "btn btn-info" })
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="row" style="font-size:large; color:chocolate; font-weight:bolder">
    <div class="element1 col-lg-3" id="val1">
    </div>
    <div class="element2 col-lg-3" id="val2">
    </div>
</div>




<script>
    var table = document.getElementById("table1"), sumVal1 = 0, sumVal2 = 0;

    for (var i = 1; i < table.rows.length; i++) {
        sumVal1 = sumVal1 + parseFloat(table.rows[i].cells[2].innerHTML);
        sumVal2 = sumVal2 + parseFloat(table.rows[i].cells[3].innerHTML);
    }
    document.getElementById("val1").innerHTML = "Qty Sum = " + sumVal1.toFixed(2);
    document.getElementById("val2").innerHTML = "Total Price Sum = " + sumVal2.toFixed(2);
</script>