Fuel/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Fuel.Models;
using Fuel.Helper;
using System.Net.Http;
using Newtonsoft.Json;
using BasicLibrary.Models;

namespace Fuel.Controllers
{
    public class VehicleController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        HelpingAPI _api = new HelpingAPI();

        public IActionResult ViewAllVehicles(string searchString)
        {
            GetMethodAsync x = new GetMethodAsync();
            if (searchString != null)
            {
                return View(x.TryHard().Result.Where(y=>y.RegistrationNr.Contains(searchString)));
            }
            else
            {
                return View(x.TryHard().Result);
            }
        }

        public async Task<IActionResult> Details(int Id)
        {
            var vehicles = new Vehicle();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync($"api/Vehicles/{Id}");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                vehicles = JsonConvert.DeserializeObject<Vehicle>(result);
            }
            return View(vehicles);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create (Vehicle vehicle)
        {
            HttpClient client = _api.Initial();
            var postTask = client.PostAsJsonAsync<Vehicle>("api/Vehicles", vehicle);
            postTask.Wait();

            var result = postTask.Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("ViewAllVehicles");
            }
            return View();
        }
  

        public async Task<IActionResult> Edit(int Id)
        {
            var vehicles = new Vehicle();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync($"api/Vehicles/{Id}");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                vehicles = JsonConvert.DeserializeObject<Vehicle>(result);
            }
            return View(vehicles);
        }


        [HttpPost]
        public IActionResult Edit(int Id, Vehicle vehicle)
        {
            HttpClient client = _api.Initial();
            var postTask = client.PutAsJsonAsync<Vehicle>($"api/Vehicles/{Id}", vehicle);
            postTask.Wait();

            var result = postTask.Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("ViewAllVehicles");
            }
            return View();
        }



        public async Task<IActionResult> Delete(int Id)
        {
            var vehicles = new Vehicle();
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync($"api/Vehicles/{Id}");
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                vehicles = JsonConvert.DeserializeObject<Vehicle>(result);
            }
            return View(vehicles);
        }


        [HttpPost]
        public async Task<IActionResult> Delete(int Id, Vehicle x)
        {
            HttpClient client = _api.Initial();
            await client.DeleteAsync($"api/Vehicles/{Id}");
            return RedirectToAction("ViewAllVehicles");
        }     






    }
}

Fuel/Views/Vehicle/Create.cshtml
@model BasicLibrary.Models.Vehicle

@{
    ViewData["Title"] = "Create";
}

<h4 style="color:purple; margin-top:50px; font-weight:bold">Create a new Vehicle Record</h4>
<hr />
<div class="row"> 
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RegistrationNr" class="control-label"></label>
                <input asp-for="RegistrationNr" class="form-control" />
                <span asp-validation-for="RegistrationNr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FuelType" class="control-label"></label>
                @Html.DropDownList("FuelType",
                    new SelectList(Enum.GetValues(typeof(FuelTypeEnum))),
                    "Select Fuel Type",
                    new { @class = "form-control" })
                <span asp-validation-for="FuelType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-primary" style="background-color:greenyellow" /> |
                @Html.ActionLink("Back to Vehicles", "ViewAllVehicles", "Vehicle", new { }, new { @class = "btn btn-outline-primary", @style = "background-color:greenyellow" })
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Fuel/Views/Vehicle/Delete.cshtml
@model BasicLibrary.Models.Vehicle

@{
    ViewData["Title"] = "Delete";
}

<h4 style="color:purple; margin-top:50px; font-weight:bold">Are you sure you want to delete this record?</h4>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationNr)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RegistrationNr)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FuelType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FuelType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-outline-primary" style="background-color:red" /> |
        @Html.ActionLink("Back to Vehicles", "ViewAllVehicles", "Vehicle", new { }, new { @class = "btn btn-outline-primary", @style = "background-color:greenyellow" })
    </form>
</div>

Fuel/Views/Vehicle/Details.cshtml
@model BasicLibrary.Models.Vehicle

@{
    ViewData["Title"] = "Details";
}

<h4 style="color:purple; margin-top:50px; font-weight:bold">Vehicle Record Details</h4>
<hr />
<div>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationNr)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RegistrationNr)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FuelType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FuelType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", "Vehicle", new { id = Model.Id }, new { @class = "btn btn-outline-primary", @style = "background-color:greenyellow" }) |
    @Html.ActionLink("Back to Vehicles", "ViewAllVehicles", "Vehicle", new { }, new { @class = "btn btn-outline-primary", @style = "background-color:greenyellow" })
</div>

Fuel/Views/Vehicle/Edit.cshtml
@model BasicLibrary.Models.Vehicle

@{
    ViewData["Title"] = "Edit";
}

<h4 style="color:purple; margin-top:50px; font-weight:bold">Edit Vehicle Record</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FuelType" class="control-label"></label>
                <input asp-for="FuelType" class="form-control" />
                <span asp-validation-for="FuelType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegistrationNr" class="control-label"></label>
                <input asp-for="RegistrationNr" class="form-control" />
                <span asp-validation-for="RegistrationNr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-outline-primary" style="background-color:greenyellow" /> |
                @Html.ActionLink("Back to Vehicles", "ViewAllVehicles", "Vehicle", new { }, new { @class = "btn btn-outline-primary", @style = "background-color:greenyellow" })
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Fuel/Views/Vehicle/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Fuel/Views/Vehicle/ViewAllVehicles.cshtml
@model IEnumerable<BasicLibrary.Models.Vehicle>

@{
    ViewData["Title"] = "ViewAllVehicles";
}


   
    <div class="input-w" style="margin-top:40px">
        <form asp-controller="Vehicle" asp-action="ViewAllVehicles">
            <p>
                <input type="button" class="btn btn-outline-primary" style="background-color:orange; margin-right:20px;" value="Create New" onclick="location.href='@Url.Action("Create", "Vehicle")'" />
                Reg. No. <input type="text" name="SearchString">
                <input type="submit" value="Filter" asp-controller="Vehicle" asp-action="ViewAllVehicles" class="btn btn-outline-primary" style="background-color:gold" />
            </p>
        </form>
    </div>

<table class="table" style="margin-top:50px; margin-bottom:50px">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FuelType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegistrationNr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Brand)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FuelType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RegistrationNr)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Brand)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Year)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Vehicle", new { id = item.Id }, new { @class = "btn btn-info" })
                    @Html.ActionLink("Detail", "Details", "Vehicle", new { id = item.Id }, new { @class = "btn btn-info" })
                    @Html.ActionLink("Delete", "Delete", "Vehicle", new { id = item.Id }, new { @class = "btn btn-info" })
                </td>
            </tr>
        }
    </tbody>
</table>